import type { QuizQuestion, ISODateTimeString } from "@/lib/types";

const now = new Date().toISOString() as ISODateTimeString;

export const QUIZ_BANK: QuizQuestion[] = [
  // BEGINNER questions
  {
    id: "q_0001",
    difficulty: "BEGINNER",
    term: "Assets",
    prompt: "무엇은 회사가 소유하고 있는 자산이나 재산을 의미하나요?",
    choices: ["부채", "자산", "지출", "수입"],
    correctIndex: 1,
    explanation: "자산(assets)은 회사나 개인이 소유하고 있는 재산입니다.",
    tags: ["accounting", "financial"],
    createdAtISO: now,
    updatedAtISO: now,
  },
  {
    id: "q_0002",
    difficulty: "BEGINNER",
    term: "Profit",
    prompt: "수익에서 비용을 뺀 것을 무엇이라고 부르나요?",
    choices: ["손실", "이익", "수익", "비용"],
    correctIndex: 1,
    explanation: "이익(profit)은 수익에서 비용을 뺀 나머지입니다.",
    tags: ["finance", "basic"],
    createdAtISO: now,
    updatedAtISO: now,
  },
  {
    id: "q_0003",
    difficulty: "BEGINNER",
    term: "Budget",
    prompt: "예정된 수입과 지출 계획을 무엇이라고 부르나요?",
    choices: ["투자", "예산", "세금", "보험"],
    correctIndex: 1,
    explanation: "예산(budget)은 미래의 수입과 지출을 계획한 것입니다.",
    tags: ["planning", "personal-finance"],
    createdAtISO: now,
    updatedAtISO: now,
  },
  {
    id: "q_0004",
    difficulty: "BEGINNER",
    term: "Tax",
    prompt: "정부에 내야 하는 의무적인 금액을 무엇이라고 부르나요?",
    choices: ["이익", "세금", "이자", "배당금"],
    correctIndex: 1,
    explanation: "세금(tax)은 정부에 내야 하는 의무적인 금액입니다.",
    tags: ["government", "finance"],
    createdAtISO: now,
    updatedAtISO: now,
  },
  {
    id: "q_0005",
    difficulty: "BEGINNER",
    term: "Saving",
    prompt: "사용하지 않고 모아두는 돈을 무엇이라고 부르나요?",
    choices: ["소비", "투자", "저축", "대출"],
    correctIndex: 2,
    explanation: "저축(saving)은 사용하지 않고 모아두는 돈입니다.",
    tags: ["personal-finance", "money"],
    createdAtISO: now,
    updatedAtISO: now,
  },
  {
    id: "q_0006",
    difficulty: "BEGINNER",
    term: "Salary",
    prompt: "일한 대가로 받는 정기적인 돈을 무엇이라고 부르나요?",
    choices: ["보너스", "급여", "이자", "배당금"],
    correctIndex: 1,
    explanation: "급여(salary)는 일한 대가로 받는 정기적인 돈입니다.",
    tags: ["income", "work"],
    createdAtISO: now,
    updatedAtISO: now,
  },

  // INTERMEDIATE questions
  {
    id: "q_0007",
    difficulty: "INTERMEDIATE",
    term: "Dividend",
    prompt: "회사 이익의 일부를 주주에게 나누어주는 것을 무엇이라고 부르나요?",
    choices: ["이자", "배당금", "수수료", "세금"],
    correctIndex: 1,
    explanation: "배당금(dividend)은 회사 이익의 일부를 주주에게 분배하는 것입니다.",
    tags: ["investing", "stocks"],
    createdAtISO: now,
    updatedAtISO: now,
  },
  {
    id: "q_0008",
    difficulty: "INTERMEDIATE",
    term: "Portfolio",
    prompt: "투자자가 보유하고 있는 여러 투자 자산의 집합을 무엇이라고 부르나요?",
    choices: ["기금", "포트폴리오", "채권", "펀드"],
    correctIndex: 1,
    explanation: "포트폴리오(portfolio)는 개인이 보유한 여러 투자 자산의 모음입니다.",
    tags: ["investing", "management"],
    createdAtISO: now,
    updatedAtISO: now,
  },
  {
    id: "q_0009",
    difficulty: "INTERMEDIATE",
    term: "Inflation",
    prompt: "시간이 지남에 따라 물가가 오르는 현상을 무엇이라고 부르나요?",
    choices: ["디플레이션", "인플레이션", "스태그플레이션", "리플레이션"],
    correctIndex: 1,
    explanation: "인플레이션(inflation)은 시간이 지남에 따라 물가가 오르는 현상입니다.",
    tags: ["economics", "macro"],
    createdAtISO: now,
    updatedAtISO: now,
  },
  {
    id: "q_0010",
    difficulty: "INTERMEDIATE",
    term: "Interest Rate",
    prompt: "돈을 빌렸을 때 내야 하는 추가 금액의 비율을 무엇이라고 부르나요?",
    choices: ["세율", "이자율", "환율", "성장률"],
    correctIndex: 1,
    explanation: "이자율(interest rate)은 빌린 돈에 대해 내야 하는 비용의 비율입니다.",
    tags: ["lending", "borrowing"],
    createdAtISO: now,
    updatedAtISO: now,
  },
  {
    id: "q_0011",
    difficulty: "INTERMEDIATE",
    term: "Risk",
    prompt: "투자에서 손실을 입을 가능성을 무엇이라고 부르나요?",
    choices: ["보상", "위험", "기회", "이득"],
    correctIndex: 1,
    explanation: "위험(risk)은 투자에서 손실을 입을 가능성을 의미합니다.",
    tags: ["investing", "safety"],
    createdAtISO: now,
    updatedAtISO: now,
  },
  {
    id: "q_0012",
    difficulty: "INTERMEDIATE",
    term: "ROI",
    prompt: "투자한 자본에 대한 이익의 비율을 무엇이라고 부르나요?",
    choices: ["ROE", "ROI", "IRR", "NPV"],
    correctIndex: 1,
    explanation: "ROI(투자수익률)는 투자한 자본에 대한 이익의 비율입니다.",
    tags: ["investing", "analysis"],
    createdAtISO: now,
    updatedAtISO: now,
  },

  // ADVANCED questions
  {
    id: "q_0013",
    difficulty: "ADVANCED",
    term: "Derivatives",
    prompt: "기초 자산의 가격 변동에 따라 가치가 결정되는 금융 상품을 무엇이라고 부르나요?",
    choices: ["선물", "파생상품", "옵션", "스왑"],
    correctIndex: 1,
    explanation: "파생상품(derivatives)은 기초 자산을 기반으로 가치가 결정되는 금융 상품입니다.",
    tags: ["advanced-finance", "derivatives"],
    createdAtISO: now,
    updatedAtISO: now,
  },
  {
    id: "q_0014",
    difficulty: "ADVANCED",
    term: "Volatility",
    prompt: "자산 가격의 변동성을 나타내는 통계적 척도를 무엇이라고 부르나요?",
    choices: ["유동성", "변동성", "수익성", "안정성"],
    correctIndex: 1,
    explanation: "변동성(volatility)은 자산 가격이 얼마나 크게 변하는지를 나타냅니다.",
    tags: ["advanced-finance", "risk"],
    createdAtISO: now,
    updatedAtISO: now,
  },
  {
    id: "q_0015",
    difficulty: "ADVANCED",
    term: "Hedging",
    prompt: "투자에서 손실을 줄이기 위해 다른 투자로 위험을 상쇄하는 전략을 무엇이라고 부르나요?",
    choices: ["차익거래", "헤징", "스프레드", "레버리지"],
    correctIndex: 1,
    explanation: "헤징(hedging)은 위험을 줄이기 위해 반대 위치의 투자를 하는 전략입니다.",
    tags: ["advanced-finance", "risk-management"],
    createdAtISO: now,
    updatedAtISO: now,
  },
  {
    id: "q_0016",
    difficulty: "ADVANCED",
    term: "Alpha",
    prompt: "시장 지수 대비 초과 수익률을 무엇이라고 부르나요?",
    choices: ["베타", "알파", "감마", "델타"],
    correctIndex: 1,
    explanation: "알파(alpha)는 시장을 초과하여 얻은 수익률입니다.",
    tags: ["advanced-finance", "performance"],
    createdAtISO: now,
    updatedAtISO: now,
  },
  {
    id: "q_0017",
    difficulty: "ADVANCED",
    term: "Arbitrage",
    prompt: "서로 다른 시장에서의 가격 차이를 이용하여 이익을 취하는 행위를 무엇이라고 부르나요?",
    choices: ["스프레딩", "차익거래", "헤징", "스텝"],
    correctIndex: 1,
    explanation: "차익거래(arbitrage)는 가격 차이를 이용한 무위험 이익 창출입니다.",
    tags: ["advanced-finance", "trading"],
    createdAtISO: now,
    updatedAtISO: now,
  },
  {
    id: "q_0018",
    difficulty: "ADVANCED",
    term: "Beta",
    prompt: "어떤 자산이 시장 변동에 얼마나 민감한지를 나타내는 계수를 무엇이라고 부르나요?",
    choices: ["알파", "베타", "감마", "세타"],
    correctIndex: 1,
    explanation: "베타(beta)는 자산이 시장 움직임에 얼마나 민감하게 반응하는지를 나타냅니다.",
    tags: ["advanced-finance", "risk-measurement"],
    createdAtISO: now,
    updatedAtISO: now,
  },
];
